/*
 * generated by Xtext 2.37.0
 */
package fr.umontpellier.qcm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QCMDslUiModule extends AbstractQCMDslUiModule {

	public QCMDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
