/*
 * generated by Xtext 2.37.0
 */
package fr.umontpellier.qcm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.umontpellier.qcm.QCMDslRuntimeModule;
import fr.umontpellier.qcm.QCMDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QCMDslIdeSetup extends QCMDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QCMDslRuntimeModule(), new QCMDslIdeModule()));
	}
	
}
