/*
 * generated by Xtext 2.37.0
 */
package fr.umontpellier.qcm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QCMDslStandaloneSetup extends QCMDslStandaloneSetupGenerated {

	public static void doSetup() {
		new QCMDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
