/*
 * generated by Xtext 2.37.0
 */
package fr.umontpellier.qcm;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QCMDslRuntimeModule extends AbstractQCMDslRuntimeModule {
}
